### PR TITLE
Task/gym search

### PR DESCRIPTION
**Pull request by codemyce**
Gym search implements a basic gym search functionality. This is incomplete since a way to query the information to be displayed needs to exist before wrapping up the functionality of this page. But this basic layout should do the trick for now

### CODE REVIEW

**Comment by WDDnguyen** [comment]
I see some view changes. Did you discuss with Volen (he has the design gym view task) about how the view should look like? I think the plan for gymActivity was to show  gyms + their equipment list + search bar. This might change how your adapter code works if he did a different design.

**Comment by codemyce** [comment]
> I see some view changes. Did you discuss with Volen (he has the design gym view task) about how the view should look like? I think the plan for gymActivity was to show gyms + their equipment list + search bar. This might change how your adapter code works if he did a different design.

I couldn't find any resource anywhere saying what we wanted it to look like so I improvised. I'll inquire with Volen.

**Comment by codemyce** [comment]
Looking at the original design, the view literally says "TO DO". So unless there are concrete suggestions on how to improve this, this design for the view should be sufficient

**Review by WDDnguyen — APPROVED** [review]
Alright. Approved until we get the gym view designed

**Pull request merged**
