### PR TITLE
displays generated workout

### PR DESCRIPTION
**Pull request by jiaweini**
It displays generated workout

### CODE REVIEW

**Comment by jiaweini** [comment]
image

**Comment by WDDnguyen** [comment]
the build failed since you didn't constraint the listview. 
image

**Comment by WDDnguyen** [comment]
So build is fine now. The view should be showing generated a workout with exercises **generated** using muscleGroups/numberOfExercises. Right now its showing the muscleGroups/numberOfExercises.
On the task list : 
Create workout from exercises chosen | S11 | Patrick Ghazal
You might want to message him to see if he has done his task so that this pull request can display the workout and the exercises chosen.

**Comment by jiaweini** [comment]
@PatrickGhazal I looked at your code. Can you add a line that could send (intent.putExtra) the user chosen workout exercise list to my WorkoutActivity page, so that i could display them? This page currently displays all generated exercises.

**Comment by jiaweini** [comment]
I don't think we have enough time. maybe let me merge and we can improve it in next sprint.

**Review by WDDnguyen — APPROVED** [review]
Need to redesign the workout activity but approved as a temporary mock up.

**Pull request merged**
