### PR TITLE
Added Activity for Home Page (xml and class)

### PR DESCRIPTION
**Pull request by bendwilletts**
Replaced boilerplate "MainActivity.java" and "activity_main.xml" files with "HomeActivity.java" and "activity_home.xml". Screenshot of the view is attached below.

I suggest merging now so that others have a better template to design off of. For now, people designing views should create a new layout (xml) file, create a class file to load the layout, and add the activity to "AndroidManifest.java". For now I left HomeActivity as the MAIN intent, which is initialized when the app is opened (It should probably be the login page once it's implemented, since we can divert already logged in users to the home page).

Gradle and misc changes were done automatically after building and running. Not sure if it can be disregarded or not.

screen shot 2019-02-12 at 3 34 41 pm

### CODE REVIEW

**Review by codemyce — APPROVED** [review]
Conventionally we should probably call it the main activity instead of the home activity. But otherwise it's good. Not the end of the world to break convention to match our models

**Comment by bendwilletts** [comment]
Honestly just wanted to differentiate between Login and Home, as either could be the MainActivity

**Comment by codemyce** [comment]
By default we want the first page to open be the main/home activity, and then redirect to the login activity. So the main page would always been the home page anyway, no? It's not a big deal, just a small convention thing tbh

**Comment by WDDnguyen** [comment]
For now, people designing views should create a new layout (xml) file, create a class file to load the layout, and add the activity to "AndroidManifest.java" . Update the README so people who work on the layout can see it.

Gradle and misc changes were done automatically after building and running. Not sure if it can be disregarded or not.
This should be fine. 

When the README is done I'll approve to be merge.

**Pull request merged**
